# Generated by Django 5.1.4 on 2025-01-17 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=70)),
                ('created_by', models.IntegerField()),
                ('valid_till', models.DateField()),
                ('create_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('message_Type', models.CharField(max_length=100)),
                ('attechment', models.FileField(blank=True, null=True, upload_to='attechment')),
                ('create_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_Date', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chatroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_room_app.chatroom')),
            ],
        ),
    ]
