# Generated by Django 5.1.4 on 2025-01-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0003_alter_chatroom_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
