# Generated by Django 5.1.4 on 2025-01-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0004_alter_chatroom_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_room_app.customers'),
        ),
    ]
