# Generated by Django 5.1.4 on 2025-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0005_alter_chat_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
