# Generated by Django 5.1.4 on 2025-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0006_alter_customers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(default='inactive', max_length=50),
        ),
    ]
