# Generated by Django 5.1.4 on 2025-01-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0010_alter_customers_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='mobile_no',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
