# Generated by Django 5.1.4 on 2025-01-31 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0021_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=70)),
                ('created_by', models.DateField(blank=True, null=True)),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('create_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
