# Generated by Django 5.1.4 on 2025-01-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0022_chatroom_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatroom_customer',
        ),
    ]
