# Generated by Django 5.1.4 on 2025-02-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0023_delete_chatroom_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
