# Generated by Django 5.1.4 on 2025-02-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0024_alter_customers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='attechment',
            field=models.FileField(blank=True, null=True, upload_to='attechment/'),
        ),
    ]
