# Generated by Django 5.1.4 on 2025-03-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room_app', '0026_remove_chat_attechment_chat_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='attachment',
        ),
        migrations.AddField(
            model_name='chat',
            name='attechment',
            field=models.FileField(blank=True, null=True, upload_to='attechment/'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
